# Generated by Django 6.0.2 on 2026-03-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasports', '0002_bucks_bulls_cavaliers_celtics_clippers_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='Gameid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
