# Generated by Django 6.0.2 on 2026-03-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasports', '0003_remove_game_id_game_gameid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bucks',
        ),
        migrations.DeleteModel(
            name='Bulls',
        ),
        migrations.DeleteModel(
            name='Cavaliers',
        ),
        migrations.DeleteModel(
            name='Celtics',
        ),
        migrations.DeleteModel(
            name='Clippers',
        ),
        migrations.DeleteModel(
            name='Grizzlies',
        ),
        migrations.DeleteModel(
            name='Hawks',
        ),
        migrations.DeleteModel(
            name='Heat',
        ),
        migrations.DeleteModel(
            name='Hornets',
        ),
        migrations.DeleteModel(
            name='Jazz',
        ),
        migrations.DeleteModel(
            name='Kings',
        ),
        migrations.DeleteModel(
            name='Knicks',
        ),
        migrations.DeleteModel(
            name='Lakers',
        ),
        migrations.DeleteModel(
            name='Magic',
        ),
        migrations.DeleteModel(
            name='Mavericks',
        ),
        migrations.DeleteModel(
            name='Nets',
        ),
        migrations.DeleteModel(
            name='Nuggets',
        ),
        migrations.DeleteModel(
            name='Pacers',
        ),
        migrations.DeleteModel(
            name='Pelicans',
        ),
        migrations.DeleteModel(
            name='Philadelphia',
        ),
        migrations.DeleteModel(
            name='Pistons',
        ),
        migrations.DeleteModel(
            name='Raptors',
        ),
        migrations.DeleteModel(
            name='Rockets',
        ),
        migrations.DeleteModel(
            name='Spurs',
        ),
        migrations.DeleteModel(
            name='Suns',
        ),
        migrations.DeleteModel(
            name='Thunder',
        ),
        migrations.DeleteModel(
            name='Timberwolves',
        ),
        migrations.DeleteModel(
            name='Trailblazers',
        ),
        migrations.DeleteModel(
            name='Warriors',
        ),
        migrations.DeleteModel(
            name='Wizards',
        ),
    ]
